[build]
  functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"

[functions.optimize]
  timeout = 26

# --- ADD REDIRECTS BELOW ---

# Force canonical URL for favicon-guide
[[redirects]]
  from = "/favicon-guide"
  to = "/favicon-guide.html"
  status = 301
  force = true

# (Optional) Disable pretty URLs site-wide if you want .html always visible
#[[redirects]]
#  from = "/*/"
#  to = "/:splat.html"
#  status = 301
