[build]
  # This tells Netlify where our functions are located.
  functions = "netlify/functions/"

[functions]
  # This ensures Node.js dependencies from the root package.json are included.
  node_bundler = "esbuild"

# --- ADD THIS NEW SECTION BELOW ---
# Increase the timeout for our specific, long-running function
[functions.optimize]
  # Set the timeout to 26 seconds (the maximum allowed is 26)
  timeout = 26