# File: netlify.toml

[build]
  # Bu satır, Netlify'a fonksiyonlarımızın nerede olduğunu net bir şekilde söyler.
  functions = "netlify/functions/"

[functions]
  # Bu ayar, fonksiyonlarımızın bağımlılıklarının doğru bir şekilde paketlenmesini sağlar.
  node_bundler = "esbuild"